services:
  solar-dashboard:
    image: ghcr.io/dubberness/solar-dashboard:latest
    container_name: solar-dashboard
    restart: unless-stopped
    ports:
      - '8420:8080'
    volumes:
      - ./data:/config
    environment:
      INVERTER_HOST: 192.168.1.8
      EVCC_URL: http://192.168.1.3:7070
      TZ: Australia/Hobart
